name: deploy projuanito.com

on:
  push:
    branches: [live]
env: 
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }} 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo "$AUTH_TOKEN"
      - run: npm i
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: live
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: build
