name: Build and deploy projuanito.com

on:
  push:
    branches: [live]
env: 
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SANITY_URL: ${{ secrets.SANITY_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: echo "$AUTH_TOKEN"
      - name: Install Sass
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: src/scss/main.scss
          destination: src/css/styles.css
      - run: npm ci
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .
          publish_branch: live-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
